	cp -f objs/nginx.dbg "/opt/keenginx-$STAMP/sbin/nginx.dbg"
	cp -f objs/nginx.orig "/opt/keenginx-$STAMP/sbin/nginx.orig"
	chmod +x /opt/keenginx-$STAMP/sbin/*
	rm -f /sbin/nginx ;
	ln -s /opt/keenginx-$STAMP/sbin/nginx /sbin/nginx
	@echo ""
	@echo "!!!! --- Keenginx version $STAMP install complete. --- !!!!"
	@echo ""
